#!/bin/bash

accounts=""

# Get a list of local accounts
local_accounts=$(dscl . -list /Users | grep -v "_")

# Check secure token status for each local account
for account in $local_accounts; do
    secure_token_status=$(sysadminctl -secureTokenStatus "$account" 2>&1 | awk '/ENABLED/ {print "Enabled"} /DISABLED/ {print "Disabled"} /UNKNOWN/ {print "Not Set"}')

    # Display result
    #echo "<result>$account - Secure Token Status: $secure_token_status</result>"
    user_status="$account - Secure Token Status: $secure_token_status"
    accounts="$accounts""$user_status
"
done
echo "<result>$accounts</result>"
